[package]
name = "swcat"
version = "0.1.0"
edition = "2024"

[lib]
name = "swcat"
path = "src/lib.rs"

[[bin]]
name = "swcat"
path = "src/main.rs"

[[bin]]
name = "swcat-tui"
path = "src/bin/swcat_tui.rs"

[dependencies]
clap      = { version = "4.6.1", features = ["derive"] }
macroquad = "0.4.14"
crossterm = "0.28"
ratatui   = "0.29"
